# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "brown sugar")
Ingredient.create(name: "limette")
Ingredient.create(name: "rum")
Ingredient.create(name: "vodka")
Ingredient.create(name: "gin")
Ingredient.create(name: "tonic")
Ingredient.create(name: "Triple Sec")
Ingredient.create(name: "whiskey")
Ingredient.create(name: "coca cola")
Ingredient.create(name: "prosecco")
Ingredient.create(name: "cucumber")
Ingredient.create(name: "pineapple")
Ingredient.create(name: "soda")
Ingredient.create(name: "water")
Ingredient.create(name: "tequila")
Ingredient.create(name: "cranberry juice")
Ingredient.create(name: "lime juice")
Ingredient.create(name: "orange juice")
Ingredient.create(name: "Curacao liqueur")
Ingredient.create(name: "grenadine syrup")
Ingredient.create(name: "Cachaca")

Cocktail.create(name: "Mojito")
Cocktail.create(name: "Long Island Ice Tea")
Cocktail.create(name: "Caipirinha")
Cocktail.create(name: "Cosmopolitan")
Cocktail.create(name: "Sex on the Beach")
Cocktail.create(name: "Tequila Sunrise")
